"""Adapter: wrap an OpenEvolve-style evaluator for SMCEvolve.

OpenEvolve evaluators have the signature

    evaluate(program_path: str) -> Dict[str, Any]

and return a dict that contains a numeric score under `combined_score`.
They import the candidate program from disk (so the candidate must
live at a real path to be `importlib`-importable).

SMCEvolve evaluators have the signature

    evaluate(program: str) -> float

and receive the program's source text directly.

`wrap_openevolve_evaluator(oe_fn)` bridges the two protocols by
writing the program string to a unique temp file, invoking
`oe_fn(tmp_path)`, pulling out `combined_score`, and cleaning up.
Any exception or missing score yields 0.0 so that malformed
programs never crash the SMC loop.

Usage inside a problem's `evaluator.py`::

    import sys
    from pathlib import Path

    _HERE = Path(__file__).parent
    if str(_HERE) not in sys.path:
        sys.path.insert(0, str(_HERE))

    from openevolve_evaluator import evaluate as _oe_evaluate
    from smcevolve.openevolve_bridge import wrap_openevolve_evaluator

    evaluate = wrap_openevolve_evaluator(_oe_evaluate)

The `openevolve_evaluator.py` file is the upstream OpenEvolve
evaluator copied verbatim (including all `verify_*`, baseline
computations, etc.) — this wrapper adds nothing to the evaluation
semantics, it only adapts the I/O shape.
"""

from __future__ import annotations

import math
import os
import tempfile
import uuid
from pathlib import Path
from typing import Any, Callable, Dict


def _coerce_score(value: Any) -> float:
    try:
        score = float(value)
    except (TypeError, ValueError):
        return 0.0
    if math.isnan(score) or math.isinf(score):
        return 0.0
    return score


def wrap_openevolve_evaluator(
    openevolve_evaluate: Callable[[str], Dict[str, Any]],
    score_key: str = "combined_score",
    workdir: str | Path | None = None,
) -> Callable[[str], float]:
    """Return an SMCEvolve `evaluate(program) -> float` adapter.

    Parameters
    ----------
    openevolve_evaluate:
        The upstream OpenEvolve evaluator. Must accept a file path
        and return a dict.
    score_key:
        Key in the returned dict that holds the scalar fitness
        (default "combined_score", which is OpenEvolve's convention).
    workdir:
        Directory in which to materialize candidate programs as
        temporary `.py` files. Defaults to the system tempdir.
        OpenEvolve's evaluators usually import the candidate by
        *module name*, so the file name must be a valid Python
        identifier — we use `oe_candidate_<uuid>.py`.
    """
    base = Path(workdir) if workdir is not None else Path(tempfile.gettempdir())
    base.mkdir(parents=True, exist_ok=True)

    def evaluate(program: str) -> float:
        token = uuid.uuid4().hex
        tmp_path = base / f"oe_candidate_{token}.py"
        try:
            tmp_path.write_text(program, encoding="utf-8")
            try:
                result = openevolve_evaluate(str(tmp_path))
            except Exception:
                return 0.0
            if not isinstance(result, dict):
                return 0.0
            return _coerce_score(result.get(score_key, 0.0))
        finally:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass
            # OpenEvolve evaluators often cache the candidate module
            # in sys.modules; drop stale entries so subsequent calls
            # re-import fresh source.
            import sys
            stale = [k for k in sys.modules
                     if k.startswith(f"oe_candidate_{token}")]
            for k in stale:
                sys.modules.pop(k, None)

    evaluate.__doc__ = (
        "SMCEvolve evaluator generated by wrap_openevolve_evaluator "
        f"(score_key={score_key!r})."
    )
    return evaluate
